{% set name = "pynimate" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynimate-{{ version }}.tar.gz
  sha256: ab29066f5e305979802e15716353d0c0af7fee2cd78845e95cace74d81727ed3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0.0
    - pip
  run:
    - python >=3.9
    - numpy
    - pandas
    - matplotlib-base
    - seaborn

test:
  imports:
    - pynimate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pynimate/
  summary: Python package for statistical data animations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
